- name: Grafana
  hosts: dk_host
  vars:
    ansible_ssh_private_key_file: /home/ftorchy/.ssh/group-stg-0_rsa
  become: yes

  tasks:
    - name: Installation and start Grafana
      include_tasks: /home/ftorchy/Documents/T-NSA-800/projet/T-NSA-800/ansible/grafana/tasks/main.yml

- name: Prometheus
  hosts: dk_host
  become: yes

  tasks:
    - name: Installation and start Prometheus
      include_tasks: /home/ftorchy/Documents/T-NSA-800/projet/T-NSA-800/ansible/prometheus/tasks/main.yml