- name: Installer docker-ce-cli
  shell: sudo apt-get install -y docker-ce-cli

- name: Install Grafana
  apt:
    name: grafana
    state: present

- name: Copy Grafana configuration
  template:
    src: /home/ftorchy/Documents/T-NSA-800/projet/T-NSA-800/ansible/grafana/templates/grafana.ini
    dest: /etc/grafana/grafana.ini

- name: Start Grafana service
  service:
    name: grafana-server
    state: started
    enabled: yes
