name: Deploy Docker Images

on:
  workflow_run:
    workflows: ["Laravel"]
    branches: [main]
    types:
      - completed

jobs:
  download-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Download Artifact
        uses: actions/download-artifact@v3
        with:
          name: docker-images

      - name: Prepare Deployment
        run: |
          mkdir -p docker_images
          # Supposant que l'artefact est un zip contenant vos images tar.
          unzip docker-images.zip -d docker_images/

      - name: Deploy to Remote Server
        run: |
          mkdir -p ansible
          echo "- hosts: remote
            tasks:
              - name: Copy Docker images
                copy:
                  src: ./docker_images/
                  dest: /home
                  owner: root
                  group: root
                  mode: '0755'
              - name: Load Docker images
                command: docker load -i /home/{{ item }}
                with_items: "{{ lookup('fileglob', './docker_images/*', wantlist=True) }}"
            become: yes" > ansible/deploy.yml
          ansible-playbook -i ./inventory.yml ansible/deploy.yml
        env:
          ANSIBLE_HOST_KEY_CHECKING: False
